import { useEffect, useState } from 'react'
import { Link, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { ArrowRight, BookOpen, Edit3, LogIn, LogOut, MapPin, Menu, Plus, Sparkles, Trash2, X } from 'lucide-react'
import { isConfigured, supabase } from './lib/supabase'
import { culture as demoCulture, destinations as demoDestinations } from './data/demo'

const navItems = [['/','Beranda'],['/budaya','Budaya'],['/wisata','Wisata'],['/tentang','Tentang']]
function usePublicData(table,fallback){const [items,setItems]=useState(fallback);useEffect(()=>{if(!isConfigured||!supabase)return;supabase.from(table).select('*').eq('status','published').order('created_at',{ascending:false}).then(({data,error})=>{if(!error&&data?.length)setItems(data)})},[table,fallback]);return items}
function Header(){const [open,setOpen]=useState(false);return <header><div className="wrap nav"><Link to="/" className="logo"><span>TP</span><b>Toraja Pusaka<small>Warisan dalam satu ruang</small></b></Link><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{navItems.map(([to,label])=><NavLink key={to} to={to} onClick={()=>setOpen(false)}>{label}</NavLink>)}<Link className="nav-cta" to="/admin/login">Admin</Link></nav></div></header>}
function Footer(){return <footer><div className="wrap footer"><div><h3>Toraja Pusaka</h3><p>Media digital untuk edukasi, promosi, dan pelestarian budaya Toraja.</p></div><div><b>Jelajahi</b><Link to="/budaya">Budaya</Link><Link to="/wisata">Wisata</Link></div><div><b>Pengelola</b><Link to="/admin/login">Login admin</Link><span>© 2026</span></div></div></footer>}
function Layout({children}){return <><Header/><main>{children}</main><Footer/></>}
function Card({item,type}){const title=item.title||item.name;return <article className="card"><div className="card-img"><img src={item.image_url} alt={title}/><span>{item.category}</span></div><div className="card-body"><h3>{title}</h3><p>{item.summary}</p>{type==='wisata'&&<small><MapPin/> {item.address}</small>}</div></article>}
function Heading({tag,title,text}){return <div className="heading"><span>{tag}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Home(){const cultures=usePublicData('cultural_contents',demoCulture);const places=usePublicData('destinations',demoDestinations);return <Layout><section className="hero"><div className="hero-bg"/><div className="wrap hero-in"><span className="kicker"><Sparkles/> Jelajah budaya Toraja</span><h1>Warisan yang hidup,<br/><em>cerita yang tak berhenti.</em></h1><p>Kenali filosofi, tradisi, seni, dan destinasi Toraja melalui pengalaman digital yang sederhana dan bermakna.</p><div className="hero-actions"><Link className="button gold" to="/budaya">Mulai menjelajah <ArrowRight/></Link><Link className="button glass" to="/wisata">Lihat destinasi</Link></div></div></section><section className="numbers"><div className="wrap"><div><b>14+</b><span>Kategori budaya</span></div><div><b>30+</b><span>Destinasi pilihan</span></div><div><b>1</b><span>Warisan bersama</span></div></div></section><section className="section wrap"><Heading tag="Pilihan budaya" title="Cerita di balik tradisi" text="Setiap bentuk, warna, dan upacara menyimpan pengetahuan yang diwariskan lintas generasi."/><div className="cards">{cultures.slice(0,3).map(x=><Card key={x.id} item={x}/>)}</div><Link className="more" to="/budaya">Lihat semua budaya <ArrowRight/></Link></section><section className="section soft"><div className="wrap"><Heading tag="Temukan Toraja" title="Kunjungi ruang budayanya" text="Destinasi yang mempertemukan lanskap, sejarah, dan kehidupan masyarakat."/><div className="cards">{places.slice(0,3).map(x=><Card key={x.id} item={x} type="wisata"/>)}</div></div></section><section className="wrap manifesto"><div><span>Pelestarian dimulai dari rasa ingin tahu</span><h2>Kenal lebih dekat.<br/>Hormati lebih dalam.</h2></div><Link className="button light" to="/tentang">Tentang proyek ini</Link></section></Layout>}
function Listing({type}){const isCulture=type==='budaya';const items=usePublicData(isCulture?'cultural_contents':'destinations',isCulture?demoCulture:demoDestinations);const [filter,setFilter]=useState('Semua');const categories=['Semua',...new Set(items.map(x=>x.category))];const shown=filter==='Semua'?items:items.filter(x=>x.category===filter);return <Layout><section className="page-head"><div className="wrap"><span>{isCulture?'Khazanah Toraja':'Jelajah Toraja'}</span><h1>{isCulture?'Budaya dan Tradisi':'Destinasi Budaya'}</h1><p>{isCulture?'Temukan makna dalam arsitektur, ritual, seni, dan keseharian masyarakat Toraja.':'Rencanakan kunjungan ke ruang tempat warisan Toraja tumbuh dan dijaga.'}</p></div></section><section className="section wrap"><div className="filters">{categories.map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="cards">{shown.map(x=><Card key={x.id} item={x} type={isCulture?'budaya':'wisata'}/>)}</div></section></Layout>}
function About(){return <Layout><section className="page-head"><div className="wrap"><span>Tentang proyek</span><h1>Ruang belajar budaya Toraja</h1><p>Sistem informasi berbasis web untuk mendukung edukasi, promosi, serta dokumentasi budaya secara berkelanjutan.</p></div></section><section className="section wrap about"><div><BookOpen/><h2>Edukasi yang mudah diakses</h2><p>Informasi disusun ringkas dan responsif untuk pelajar, wisatawan, akademisi, dan masyarakat umum.</p></div><div><MapPin/><h2>Promosi bertanggung jawab</h2><p>Destinasi diperkenalkan bersama konteks budaya agar kunjungan tumbuh menjadi penghargaan.</p></div><div><Sparkles/><h2>Pelestarian digital</h2><p>Konten dapat diperbarui administrator sehingga dokumentasi terus berkembang bersama masyarakat.</p></div></section></Layout>}
function Login(){const nav=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');async function submit(e){e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);else nav('/admin')}return <div className="login"><Link to="/" className="logo"><span>TP</span><b>Toraja Pusaka<small>Panel administrator</small></b></Link><form onSubmit={submit}><LogIn/><h1>Selamat datang</h1><p>Masuk menggunakan akun administrator Supabase.</p>{error&&<div className="error">{error}</div>}<label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Kata sandi<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button dark">Masuk</button><Link to="/">Kembali ke website</Link></form></div>}
function Guard({children}){const [session,setSession]=useState(undefined);useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);if(session===undefined)return <div className="loading">Memuat…</div>;return session?children:<Navigate to="/admin/login"/>}
const resourceMap={budaya:{table:'cultural_contents',title:'Konten Budaya',name:'title',fields:['title','slug','category','summary','body','image_url']},wisata:{table:'destinations',title:'Destinasi Wisata',name:'name',fields:['name','slug','category','summary','address','image_url']}}
function Admin(){const nav=useNavigate();const [kind,setKind]=useState('budaya');const [rows,setRows]=useState([]);const [editing,setEditing]=useState(null);const resource=resourceMap[kind];async function load(){const {data}=await supabase.from(resource.table).select('*').order('created_at',{ascending:false});setRows(data||[])}useEffect(()=>{supabase.from(resource.table).select('*').order('created_at',{ascending:false}).then(({data})=>setRows(data||[]))},[resource.table]);async function save(e){e.preventDefault();const payload={...editing};delete payload.id;delete payload.created_at;delete payload.updated_at;const q=editing.id?supabase.from(resource.table).update(payload).eq('id',editing.id):supabase.from(resource.table).insert(payload);const {error}=await q;if(error)return alert(error.message);setEditing(null);load()}async function remove(id){if(confirm('Hapus data ini?')){await supabase.from(resource.table).delete().eq('id',id);load()}}async function logout(){await supabase.auth.signOut();nav('/')}return <div className="admin"><aside><div className="logo inverse"><span>TP</span><b>Toraja Pusaka<small>Administrator</small></b></div><button className={kind==='budaya'?'active':''} onClick={()=>setKind('budaya')}>Konten budaya</button><button className={kind==='wisata'?'active':''} onClick={()=>setKind('wisata')}>Destinasi wisata</button><button className="logout" onClick={logout}><LogOut/> Keluar</button></aside><section><div className="admin-head"><div><span>Supabase Admin</span><h1>{resource.title}</h1></div><button className="button dark" onClick={()=>setEditing({status:'published'})}><Plus/> Tambah</button></div><div className="table"><table><thead><tr><th>Judul/Nama</th><th>Kategori</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x[resource.name]}</b><small>{x.slug}</small></td><td>{x.category}</td><td><i className={x.status}>{x.status}</i></td><td><button onClick={()=>setEditing(x)}><Edit3/></button><button onClick={()=>remove(x.id)}><Trash2/></button></td></tr>)}</tbody></table>{!rows.length&&<p className="empty">Belum ada data.</p>}</div></section>{editing&&<div className="modal"><form onSubmit={save}><div className="modal-title"><h2>{editing.id?'Ubah':'Tambah'} {resource.title}</h2><button type="button" onClick={()=>setEditing(null)}><X/></button></div>{resource.fields.map(f=><label key={f}>{f.replace('_',' ')}{['summary','body'].includes(f)?<textarea required={f==='summary'} value={editing[f]||''} onChange={e=>setEditing({...editing,[f]:e.target.value})}/>:<input required={!['image_url','address'].includes(f)} value={editing[f]||''} onChange={e=>setEditing({...editing,[f]:e.target.value})}/>}</label>)}<label>Status<select value={editing.status||'draft'} onChange={e=>setEditing({...editing,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option></select></label><button className="button dark">Simpan</button></form></div>}</div>}
export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/budaya" element={<Listing type="budaya"/>}/><Route path="/wisata" element={<Listing type="wisata"/>}/><Route path="/tentang" element={<About/>}/><Route path="/admin/login" element={<Login/>}/><Route path="/admin" element={<Guard><Admin/></Guard>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}
